version: '3.9'
services:        
  app-energisa:
     build: 
        context: .
        dockerfile: Dockerfile     
     image: jupyter-lab
     container_name: jupyter
     env_file:
      - .env  
     depends_on:
         - db
     links:
            - db      
     ports:
            - "8888:8888"     
     volumes:
      - ./app:/usr/src/app
     # mantém o container aberto, se o mesmo não executa um script
     tty: true

  postgres-init:
    image: postgres
    volumes:
      - "postgres_data:/data"
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /data

  db:    
    depends_on:
      postgres-init:
        condition: service_started
    image: postgres
    env_file:
      - .env      
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PWD_POSTGRES}
      POSTGRES_DB: ${DATABASE_POSTGRES}
      PGDATA: /pgdata
          
    volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - "postgres_data:/pgdata"
    user: "2000"    
    restart: unless-stopped

  pgadmin:
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: ${EMAIL_PGADMIN}
         PGADMIN_DEFAULT_PASSWORD: ${PWD_PGADMIN}
      ports:
         - "16543:80"
      depends_on:
         - db
      networks:
         - db   
networks:
   db:
      driver: bridge

volumes:
  postgres_data:
  pgadmin:

